project:
  type: book
  output-dir: docs 

book:
  title: "Applying the Histogram of Oriented Gradients Algorithm for Detecting Grass Lay Direction"
  author: "Ben Sunshine"
  date: "5/10/2024"
  chapters:
    - index.qmd
    - data.qmd
    - methods.qmd
    - part: "Results"
      chapters:
        - aerial_images_results.qmd
        - grass_images_results.qmd
        - backflip_image_results.qmd
    - conclusion.qmd
    - references.bib

bibliography: references.bib

format:
  html:
    number-sections: true
    number-depth: 0
    code-fold: true
    code-tools: true
    code-line-numbers: true
    toc: true
    theme: 
      light: cosmo
      dark: darkly
  pdf:
    toc: true
    documentclass: scrreprt
    bibliography: references.bib
    csl: apa-6th-edition.csl
    include-in-header: 
      text: |
        \let\oldsection\section
        \renewcommand\section{\clearpage\oldsection}
    
  docx: 
    toc: true
    bibliography: references.bib
    csl: apa-6th-edition.csl
    number-sections: true
    number-depth: 0
    date: "2024-05-10"
    abstract-title: "Abstract"
    fig-align: center

  
editor: visual