project:
  type: book
  output-dir: docs

book:
  title: "Applying the Histogram of Oriented Gradients Algorithm for Detecting Grass Lay Direction"
  author: "Ben Sunshine"
  date: "5/10/2024"
  chapters:
    - index.qmd
    - data.qmd
    - methods.qmd
    - part: "Results"
      chapters:
        - aerial_images_results.qmd
        - grass_images_results.qmd
        - backflip_image_results.qmd
    - conclusion.qmd

bibliography: references.bib

format:
  html:
    number-depth: 0
    code-fold: true
    code-tools: true
    code-line-numbers: true
    toc: true
    theme: 
      light: cosmo
      dark: darkly
  pdf:
    toc: true
    documentclass: scrreprt
  
editor: visual