project:
  type: book
  output-dir: docs

book:
  title: "Applying the Histogram of Oriented Gradients Algorithm for Detecting Grass Lay Direction"
  author: "Ben Sunshine"
  date: "5/10/2024"
  chapters:
    - index.qmd
    - data.qmd
    - methods.qmd
    - results.qmd
    - conclusion.qmd

bibliography: references.bib

format:
  html:
    code-fold: true
    code-tools: true
    code-line-numbers: true
    toc: true
    embed-resources: true
    theme: 
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt
  
editor: visual
