---
title: "Conclusion"
author: "Ben Sunshine"
---

|       In this study, the Histogram of Oriented Gradients (HOG) algorithm was utilized to analyze a variety of images, including those sourced from both the internet and St. Lawrence University. Our objective was to extract dominant angles from these images and assess the algorithm's potential for automating the manual grass lay measurement technique performed by Dr. Rosales and his team. Their research focuses on correlating grass lay direction with predominant wind data, locally at St. Lawrence University, to evaluate potential shifts in prevailing Arctic wind patterns observed by indigenous communities. The HOG algorithm was successful in identifying patterns, streets, edges, and grass lay angles from various images. Images with visually dominant angles were evaluated accurately by the algorithm. Even in scenarios where images introduced increased variability, such as the aerial Living Laboratory and skiing image, visual patterns were reflected by the polar histograms. 

|       While the HOG algorithm proved effective, it does come with limitations. Although it can identify the axis of a gradient's angle, it lacks the capability to determine the direction of a gradient's angle. This occurs because the inverse tangent function used to calculate a gradient's angle using the x-gradient and y-gradient components can only produce angles between 0 and 180 degrees. This poses potential challenges when counting angle frequencies, as any angle with a directional component surpassing 180 degrees gets conflated with its corresponding angle below 180 degrees. In order to achieve optimal results, it is best to use images with relatively square aspect ratios, higher zoom levels, and consistent lighting. As seen in the Salt Lake City image, having a predominantly rectangular aspect ratio can accentuate the frequency of angles in a certain direction because they naturally have a higher occurrence. Zoom level played a critical role when analyzing the aerial cityscapes, as San Francisco emerged having the most accurate results with its slightly diagonal grid layout. Lastly, the skiing image highlighted the impact of object brightness on polar plots. Specifically for the distributed binning technique, images featuring brighter objects tended have higher frequencies of corresponding gradient angles because of their increased gradient magnitudes.

|       In conclusion, our findings visualize the efficacy of the Histogram of Oriented Gradients (HOG) algorithm in extracting gradient angles from various images, particularly lay angles from grass images. To further validate the results from this study, the next step entails a comparison between the results generated by the HOG algorithm's polar plots and the manually measured angles by Dr. Rosales' team. Additionally, future comparison of aerial grass images with corresponding wind data is necessary to apply this methodology on St. Lawrence Island, AK to facilitate more efficient data collection and analysis.





# Bibliography {-}
