---
title: "Introduction"
author: "Ben Sunshine"
---
|       Subsistence-oriented indigenous communities across Alaska rely heavily on Traditional Ecological Knowledge (TEK), a holistic understanding of their environment acquired through generations of observation and cultural transmission. Among the Anishinaabek tradition, sweetgrass symbolizes wisdom and knowledge, passed down from elders to younger generations. Indigenous hunters and gatherers have long observed the alignment of grass and plants after the growing season as indicative of prevailing wind directions. Predominant wind direction serve a crucial role to subsistence practitioners when hunting, fishing, settling, and keeping track of changing weather. On islands like St. Lawrence Island in Savoonga, AK, natives have observed a shift from historically predominant northerly wind patterns to southerly and easterly and dominated winds. This hypothesis has not yet been confirmed, due to the absence of weather stations.
|       This research project seeks to reinforce Traditional Ecological Knowledge (TEK) with Scientific Ecological Knowledge (SEK) to develop our understanding of Alaskan indigenous wisdom and its correlation with modern scientific findings. By employing advanced image processing and machine learning techniques on imaging data obtained from the Living Laboratory at St. Lawrence University, we aim to utilize a Histogram of Oriented Gradients (HOG) algorithm to enhance the methodology of data collection and measure the predominant direction in which grass lays after its growing season. This interdisciplinary approach not only deepens our comprehension of indigenous knowledge systems but also sheds light on environmental dynamics and climate change impacts in remote regions.
